/* Automatically generated by configure - do not modify */
#define CONFIG_QE_PREFIX "/usr/local"
#define QE_VERSION "0.3.3"
#define CONFIG_NETWORK 1
#define CONFIG_X11 1
#define CONFIG_XV 1
#define CONFIG_HTML 1
#define CONFIG_DLL 1
#define CONFIG_UNICODE_JOIN 1
#define CONFIG_ALL_KMAPS 1
