/* Automatically generated file - do not edit */
const char docbook_style[] =
"abstract,ackno,address,affiliation,alt,answer,appendix,areaspec,"
"arg,article,attribution,audioobject,author,authorblurb,authorgro"
"up,beginpage,bibliodiv,biblioentry,bibliography,bibliomixed,bibl"
"iomset,biblioset,blockquote,book,bookbiblio,bridgehead,callout,c"
"alloutlist,caption,caution,chapter,city,cmdsynopsis,collab,colop"
"hon,comment,confdates,confgroup,confnum,confsponsor,conftitle,co"
"ntractnum,contractsponsor,contrib,copyright,corpauthor,corpname,"
"country,dedication,edition,editor,epigraph,equation,example,figu"
"re,firstname,footnote,formalpara,funcprototype,funcsynopsis,func"
"synopsisinfo,glossary,glossdef,glossentry,glosslist,glosssee,glo"
"ssseealso,graphic,graphicco,group,highlights,holder,honorific,im"
"ageobject,imageobjectco,important,index,indexdiv,indexentry,info"
"rmalequation,informalexample,informalfigure,issuenum,itemizedlis"
"t,itermset,jobtitle,keywordset,legalnotice,lineage,listitem,lite"
"rallayout,lot,lotentry,mediaobject,mediaobjectco,member,msg,msga"
"ud,msgentry,msgexplan,msginfo,msglevel,msgmain,msgorig,msgrel,ms"
"gset,msgsub,msgtext,note,orderedlist,otheraddr,othercredit,other"
"name,para,part,partintro,phone,pob,postcode,preface,primaryie,pr"
"inthistory,procedure,programlisting,programlistingco,publisher,p"
"ublishername,qandadiv,qandaentry,qandaset,question,refclass,refd"
"escriptor,refentry,refentrytitle,reference,refmiscinfo,refname,r"
"efnamediv,refsect1,refsect2,refsect3,refsynopsisdiv,releaseinfo,"
"revhistory,revision,revremark,sbr,screen,screenco,screenshot,sec"
"ondaryie,sect1,sect2,sect3,sect4,sect5,section,seealsoie,seeie,s"
"eglistitem,segmentedlist,set,setindex,shortaffil,sidebar,simpara"
",simplelist,simplesect,state,step,street,subject,subjectset,subj"
"ectterm,substeps,subtitle,surname,synopfragment,synopfragmentref"
",synopsis,term,tertiaryie,textobject,tip,title,toc,tocback,tocch"
"ap,tocentry,tocfront,toclevel1,toclevel2,toclevel3,toclevel4,toc"
"level5,tocpart,variablelist,varlistentry,videoobject,warning{dis"
"play:block;}articleinfo,bookinfo,docinfo,objectinfo,refmeta,refs"
"ect1info,refsect2info,refsect3info,refsynopsisdivinfo,screeninfo"
",sect1info,sect2info,sect3info,sect4info,sect5info,sectioninfo,s"
"etinfo,titleabbrev,indexterm{display:none;}chapter>title,glossar"
"y>title{font-size:2em;font-weight:bold;color:maroon;margin-top:."
"67ex;margin-bottom:.67ex;}chapter{counter-increment:chap;counter"
"-reset:sect1}chapter>title:before{content:\"Chapter \"counter(chap"
",upper-roman)\"\\A\";}article>title{font-size:2em;margin-top:.67ex;"
"margin-bottom:.67ex;text-align:center;}subtitle{font-weight:bold"
";color:maroon;margin-top:1.33ex;margin-bottom:1.33ex;}article>su"
"btitle{text-align:center;}sect1>title,sect2>title,sect3>title,se"
"ct4>title,sect5>title,section>title{font-weight:bold;color:maroo"
"n;}sect1>title,section>title{font-size:1.5em;margin-top:.83ex;ma"
"rgin-bottom:.83ex;}sect2>title,section section>title{font-size:1."
"17em;margin-top:1ex;margin-bottom:1ex;}sect3>title,sect4>title,s"
"ect5>title,section section section>title,section section*section>ti"
"tle{font-size:1em;margin-top:1.33ex;margin-bottom:1.33ex;}sect1,"
"section{counter-increment:sect1}sect1>title:before,section>title"
":before{content:counter(chap)\".\"counter(sect1)\" \";}sect2,section"
" section{counter-increment:sect2}sect2>title:before,section sectio"
"n>title:before{content:counter(chap)\".\"counter(sect1)\".\"counter("
"sect2)\" \";}sect3,section section section{counter-increment:sect3}s"
"ect3>title:before,section section section>title:before{content:cou"
"nter(chap)\".\"counter(sect1)\".\"counter(sect2)\".\"counter(sect3)\" \""
";}sect4,section section section section{counter-increment:sect4}sec"
"t4>title:before,section section section section>title:before{conten"
"t:counter(chap)\".\"counter(sect1)\".\"counter(sect2)\".\"counter(sect"
"3)\".\"counter(sect4)\" \";}section section section*section>title:befo"
"re{content:\"\";}table,informaltable{display:block;margin-top:1.33"
"ex;margin-bottom:1.33ex;}table>title{font-style:italic;text-alig"
"n:center;margin-left:2ex;margin-right:2ex;margin-bottom:2ex;}tgr"
"oup{display:table;border:1px outset gray;text-align:eval(attr(alig"
"n));}colspec,spanspec{display:table-column;}thead,tbody,tfoot{di"
"splay:table-row-group;vertical-align:eval(attr(valign));}row{dis"
"play:table-row;vertical-align:eval(attr(valign));}entry{display:"
"table-cell;text-align:eval(attr(align));vertical-align:eval(attr"
"(valign));border:1px inset gray;padding:2px;}entry>*:first-child{m"
"argin-top:0;margin-bottom:0;}entrytbl{display:table;border:1px in"
"set gray;padding:2px;}para,simpara,formalpara{margin-top:1.33ex;m"
"argin-bottom:1.33ex;}formalpara>*{margin-top:0;margin-bottom:0;}"
"formalpara>title{font-weight:bold;}listitem>*:first-child{margin"
"-top:0;margin-bottom:0;}itemizedlist{margin-left:2ex;margin-top:"
"1.33ex;margin-bottom:1.33ex;}itemizedlist>listitem{margin-left:2"
".5ex;}itemizedlist>listitem:before{display:marker;content:disc;}"
"itemizedlist>listitem itemizedlist>listitem:before{display:marker"
";content:square;}itemizedlist>listitem itemizedlist>listitem itemi"
"zedlist>listitem:before{display:marker;content:icon(diamond);}it"
"emizedlist>listitem itemizedlist>listitem itemizedlist>listitem ite"
"mizedlist>listitem:before{display:marker;content:circle;}ordered"
"list{margin-left:2ex;margin-top:1.33ex;margin-bottom:1.33ex;}ord"
"eredlist>listitem{margin-left:6ex;}orderedlist>listitem:before{d"
"isplay:marker;counter-increment:n;content:counter(n,decimal);fon"
"t-weight:bold;}orderedlist[numeration=loweralpha]>listitem:befor"
"e{display:marker;content:counter(n,lower-alpha);counter-incremen"
"t:n;}orderedlist[numeration=upperalpha]>listitem:before{display:"
"marker;content:counter(n,upper-alpha);counter-increment:n;}order"
"edlist[numeration=lowerroman]>listitem:before{display:marker;cou"
"nter-increment:n;content:counter(n,lower-roman);}orderedlist[num"
"eration=upperroman]>listitem:before{display:marker;counter-incre"
"ment:n;content:counter(n,upper-roman);}variablelist{margin-left:"
"2ex;margin-top:1.33ex;margin-bottom:1.33ex;}varlistentry>term{fo"
"nt-weight:bold;}varlistentry>listitem{margin-left:4ex;}glossentr"
"y{margin-top:1.33ex;margin-bottom:1.33ex;}glossentry>glossterm{d"
"isplay:block;font-style:italic;}glossdef{margin-left:4ex;}glossd"
"ef>*:first-child{margin-top:0;margin-bottom:0;}qandaentry{margin"
"-top:1.33ex;margin-bottom:1.33ex;}question{font-style:italic;}qu"
"estion,answer{margin-left:4ex;}question:before{content:\"Q:\";disp"
"lay:marker;color:olive;font-weight:bold;font-style:normal;}answe"
"r:before{content:\"A:\";display:marker;color:olive;font-weight:bol"
"d;}question>*:first-child,answer>*:first-child{margin-top:0;marg"
"in-bottom:0;}simplelist{margin-left:4ex;}member{margin-left:2.5e"
"x;}note{margin-left:10ex;}note:before{content:\"note \";display:ma"
"rker;color:olive;}tip{margin-left:10ex;}tip:before{content:\"tip "
"\";display:marker;color:olive;}footnote{font-size:.83em;margin-le"
"ft:15ex;margin-right:5ex;}footnote:before{content:\"footnote \";di"
"splay:marker;color:olive;}programlisting,screen{white-space:pre;"
"background-color:#E0E0E0;border:thin solid gray;font-family:monosp"
"ace;font-size:.83em;margin-top:1.33ex;margin-bottom:1.33ex;}prog"
"ramlistingco{border:1 solid gray;padding:1ex;margin-top:1.33ex;mar"
"gin-bottom:1.33ex;}programlistingco programlisting{border-style:n"
"one;}areaspec:before{content:\"areas \";color:olive;}area,co{count"
"er-increment:n;content:\"(\"counter(n)\")\";color:olive;}callout{mar"
"gin-left:6ex;}callout>*:first-child{margin-top:0;margin-bottom:0"
";}calloutlist>callout:before{display:marker;counter-increment:n;"
"content:\"(\"counter(n)\")\";color:olive;}figure,mediaobject{text-al"
"ign:center;margin-left:auto;margin-right:auto;margin-top:1.33ex;"
"margin-bottom:1.33ex;}figure>title,caption{font-style:italic;}ca"
"ption>*:first-child{margin-top:0;margin-bottom:0;}graphic,imaged"
"ata{content:image(attr(fileref),-400,-200);}graphic{margin-left:"
"auto;margin-right:auto;}blockquote{margin-left:10ex;margin-right"
":10ex;margin-top:1.33ex;margin-bottom:1.33ex;}blockquote>title,a"
"ttribution{font-style:italic;}attribution{text-align:right;}attr"
"ibution:before{content:\"-- \"}emphasis{font-style:italic;}emphasi"
"s[role=bold]{font-style:normal;font-weight:bold;}literal,filenam"
"e,command,envar,parameter{font-family:monospace;font-size:.83em;"
"}parameter,replaceable{font-style:italic;}anchor:after{content:i"
"con(left-target);vertical-align:text-top;color:olive;}link,ulink"
",email{color:navy;text-decoration:underline;}xref{content:icon(r"
"ight-link);vertical-align:text-top;color:navy;}foreignphrase{fon"
"t-style:italic;}sgmltag{color:red;}sgmltag[class=\"starttag\"]:bef"
"ore{content:\"<\";}sgmltag[class=\"endtag\"]:before{content:\"</\";}sg"
"mltag[class=\"starttag\"]:after,sgmltag[class=\"endtag\"]:after{cont"
"ent:\">\";}quote:before{content:open-quote;}quote:after{content:cl"
"ose-quote;}@media print{articleinfo,bookinfo,docinfo,objectinfo,r"
"efmeta,refsect1info,refsect2info,refsect3info,refsynopsisdivinfo"
",screeninfo,sect1info,sect2info,sect3info,sect4info,sect5info,se"
"ctioninfo,setinfo,titleabbrev,indexterm{display:none;}colspec,sp"
"anspec{display:none;}*{background-color:transparent;line-height:"
"1.2;}programlisting,screen{background-color:#FFFFE0;border:1px so"
"lid#E0E0A0;}graphic,imagedata{content:image(attr(fileref),-500,-"
"700,smooth);}}"
;

